### ISSUE TITLE
Doesn't work with notebook 7

### ISSUE THREAD

**Issue by yuvipanda** [jupyterlab-contrib/jupyterlab-open-url-parameter#14]
## Description

I'd love for this to work with notebook 7 as well, rather than just JupyterLab. I see notebook 7 also has the 'open from URL' functionality, so hopefully it's a reasonably simple matter?

**Comment by yuvipanda** [comment]
Maybe https://github.com/jupyterlab-contrib/jupyterlab-open-url-parameter/blob/f216f9dfb5ad916ee6fb3d6197c86abacd46829c/src/index.ts#L12?

**Comment by yuvipanda** [comment]
https://notebooksharing.space/jupyterlite/lab/?fromURL=/api/v1/notebook/003d600c569502a28ab39b0fe4d4ea16cedcdcbc400f3093d76fc5e48f061246/Demo.ipynb works, but https://notebooksharing.space/jupyterlite/tree/?fromURL=/api/v1/notebook/003d600c569502a28ab39b0fe4d4ea16cedcdcbc400f3093d76fc5e48f061246/Demo.ipynb does not

**Comment by jtpio** [comment]
> Maybe
> 
> https://github.com/jupyterlab-contrib/jupyterlab-open-url-parameter/blob/f216f9dfb5ad916ee6fb3d6197c86abacd46829c/src/index.ts#L12
> ?

Yeah that may be because of this indeed.

Notebook 7 should indeed be supported.

**Comment by yuvipanda** [comment]
@jtpio do you think you'll have any capacity to look into it? :D :D
